#ifndef MANDELBROT_H_INCLUDED
#define MANDELBROT_H_INCLUDED

#include "MANDELBROT_csr.h"

// READ and WRITE macros for the component
#define MANDELBROT_READ(offset)               IORD_32DIRECT  (MANDELBROT_0_MANDELBROT_INTERNAL_INST_BASE, offset)
#define MANDELBROT_WRITE(offset, data)        IOWR_32DIRECT  (MANDELBROT_0_MANDELBROT_INTERNAL_INST_BASE, offset, data)

#define onchip_memory_READ(offset) 		      IORD_32DIRECT  (ONCHIP_MEMORY2_0_BASE, offset)
#define onchip_memory_WRITE(offset, data)     IOWR_32DIRECT  (ONCHIP_MEMORY2_0_BASE, offset, data)


// READ and WRITE macros for the component memory (make sure correct bit-precision for macro is used)
//#define MANDELBROT_memory_READ(offset)        IORD_32DIRECT  (FILTER_0_IMAGE_FILTER_INTERNAL_INST_AVS_PIXEL_DATA_BASE, offset)
//#define MANDELBROT_memory_WRITE(offset, data) IOWR_32DIRECT  (FILTER_0_IMAGE_FILTER_INTERNAL_INST_AVS_PIXEL_DATA_BASE, offset, data)

// Component register macros
#define MANDELBROT_enable_interrupt()       MANDELBROT_WRITE  	(MANDELBROT_CSR_INTERRUPT_ENABLE_REG, MANDELBROT_CSR_INTERRUPT_ENABLE_MASK & 0x1)
#define MANDELBROT_disable_interrupt()      MANDELBROT_WRITE  	(MANDELBROT_CSR_INTERRUPT_ENABLE_REG, MANDELBROT_CSR_INTERRUPT_ENABLE_MASK & 0x0)
#define MANDELBROT_clear_done_status()      MANDELBROT_WRITE  	(MANDELBROT_CSR_INTERRUPT_STATUS_REG, MANDELBROT_CSR_INTERRUPT_STATUS_MASK & 0x1)
#define MANDELBROT_start()                  MANDELBROT_WRITE  	(MANDELBROT_CSR_START_REG, MANDELBROT_CSR_START_MASK & 0x1)
#define MANDELBROT_busy()                   MANDELBROT_READ   	(MANDELBROT_CSR_BUSY_REG) & MANDELBROT_CSR_BUSY_MASK
#define MANDELBROT_done()                   MANDELBROT_READ   	(MANDELBROT_CSR_INTERRUPT_STATUS_REG) & MANDELBROT_CSR_INTERRUPT_STATUS_MASK
#define MANDELBROT_returndata()				MANDELBROT_READ		(MANDELBROT_CSR_RETURNDATA_REG)& MANDELBROT_CSR_RETURNDATA_MASK

//#define MANDELBROT_WRITE_REAL0_REG(data)	MANDELBROT_WRITE	(MANDELBROT_CSR_ARG_REAL0_REG, MANDELBROT_CSR_ARG_REAL0_MASK & data)
//#define MANDELBROT_WRITE_IMAG_REG(data)		MANDELBROT_WRITE	(MANDELBROT_CSR_ARG_IMAG_REG, MANDELBROT_CSR_ARG_IMAG_MASK & data)

#define MANDELBROT_WRITE_REAL0_REG(data)	MANDELBROT_WRITE	(MANDELBROT_CSR_ARG_REAL0_REG, data)
#define MANDELBROT_WRITE_IMAG_REG(data)		MANDELBROT_WRITE	(MANDELBROT_CSR_ARG_IMAG_REG, data)
#define MANDELBROT_WRITE_Z_REAL_REG(data)	MANDELBROT_WRITE	(MANDELBROT_CSR_ARG_Z_REAL_REG, data)
#define MANDELBROT_WRITE_Z_IMAG_REG(data)	MANDELBROT_WRITE	(MANDELBROT_CSR_ARG_Z_IMAG_REG, data)

#define MANDELBROT_READ_REAL0_REG()			MANDELBROT_READ		(MANDELBROT_CSR_ARG_REAL0_REG) & MANDELBROT_CSR_ARG_REAL0_MASK
#define MANDELBROT_READ_IMAG_REG()			MANDELBROT_READ	  	(MANDELBROT_CSR_ARG_IMAG_REG) & MANDELBROT_CSR_ARG_IMAG_MASK


#endif
